### ISSUE TITLE
Problem with Lets Encrypt Certificates and the Git client

### ISSUE THREAD

**Issue by strausmann** [apolopena/gitpod-laravel-starter#200] opened 2022-02-08 21:11 UTC
### Describe the bug

I have found a bug in the release 1.4.0 and 1.5.0 unfortunately in connection with the Git Client and Lets Encrypt Certificates. I have a self-hosted GitLab server.

Unfortunately, when I do a Git push, I get the following error message: 
fatal: unable to access 'https://git.isp-serverfarm.de/laravel-training/laravel-blog-v2.git': server certificate verification failed. CAfile: none CRLfile: none

### Screenshots

![image](https://user-images.githubusercontent.com/4519228/153075511-e431115f-c44e-40ef-a5f2-2d88dc65edc7.png)

### Steps to reproduce

Use Gitlab self-hosted with lets encrypt certificates and load the workspace as usual.

### Expected behavior

A simple "sudo update-ca-certificates" does not work. Also the URL https://git.isp-serverfarm.de can be accessed with curl or wget without problems. Only the Git client itself has a problem with it.

**Comment by apolopena** [comment] 2022-02-09 00:02
There are alot of moving parts on this one from me to even to be able to test it out. Not super sure where to start.

**Comment by apolopena** [comment] 2022-02-09 00:03
Something along the lines of this?
https://docs.gitlab.com/ee/integration/gitpod.html

**Comment by apolopena** [comment] 2022-02-09 00:06
Did you register your self hosted gitlab instance with Gitpod?
https://www.gitpod.io/docs/gitlab-integration#registering-a-self-hosted-gitlab-installation

**Comment by strausmann** [comment] 2022-02-09 06:22
I've been using GitPod with my GitLab self-hosted instance since GitPod first supported it.

So I don't see any problem with the GitPod integration at the moment. 
I think GitPod has changed something in the base image again and that's why the build doesn't work anymore.

However, I just created a new repository and then used the "gitpod/workspace-mysql" image as a base. Here there are no problems when pushing to the gitlab instance from me.

![image](https://user-images.githubusercontent.com/4519228/153133502-d588c02b-8cb1-41ca-8571-d7047da3dfeb.png)

**Comment by strausmann** [comment] 2022-02-09 06:53
So, I tried something again. Changed the base image to this day.

FROM gitpod/workspace-mysql:legacy-dazzle-v1

With this, both the build of the workspace and my git push works again.

**Comment by strausmann** [comment] 2022-02-09 07:05
Ok, have to correct myself a bit. With the <code>FROM gitpod/workspace-mysql:legacy-dazzle-v1</code> only the 1.4.0 image works again. With the 1.5.0 image I still have problems with the Git client and my own GitLab instance.

**Comment by apolopena** [comment] 2022-02-09 16:58
Ok we can fix this by pinning the Gitpod workspace-mysql image version to a specific date:
https://github.com/gitpod-io/workspace-images/issues/595#issuecomment-1033951855

Not my favorite solution but perhaps we can create and maintain our own underlying image in the future.

**Comment by apolopena** [comment] 2022-02-09 19:43
@strausmann 
Can you try this development branch in gitlab and verify the fix?

**Comment by apolopena** [comment] 2022-02-09 20:08
workspace-mysql::2022-02-04-10-54-10 did not work for me

**Comment by apolopena** [comment] 2022-02-09 20:30
It looks like there is no version of `workspace-mysql` where nginx, PHP, and Apache are retained but ca certificates work. Since these are the only two tags we have to work with:
(contains nginx, PHP and apache but has buggy ca certificates)
https://hub.docker.com/layers/gitpod/workspace-mysql/legacy-dazzle-v1/images/sha256-d75a730768eba3eacf854e4dd671967a2c07d81cee44ec51e85c1265ec1b2baf?context=explore
and
(does not contain nginx, PHP and apache but ca certificates are fixed?)
https://hub.docker.com/layers/gitpod/workspace-mysql/2022-02-04-10-54-10/images/sha256-89974ad5bffbd7f1a5f68070f81e414d9a4d1be923d0b606177711462c83c1df?context=explore

Please advise how I can workaround this.

Its looking like I will have to use `workspace-full` and then integrate mysql on my own? I would really rather not do that to hotfix this breaking change in a bunch of my projects, including portfolio pieces.

**Comment by apolopena** [comment] 2022-02-09 20:35
@strausmann 
I am hoping for a suggested workaround (from Gitpod) that actually works.

Otherwise I will have to integrate mysql in this projects `gitpod.Dockerfile` and build the project on `workspace-full:some pinned-date`.

Thoughts?

**Comment by apolopena** [comment] 2022-02-10 16:35
@strausmann 
Gitpod fixed this issue. I reverted the hotfix. Let me know if you still see this issue in v1.5.0
Thanks!

**Comment by apolopena** [comment] 2022-03-05 19:41
@strausmann
I will assume this has been fixed since it was a regression issue that was addressed by Gitpod.
Feel free to re-open this after [v.16](https://github.com/apolopena/gitpod-laravel-starter/milestone/6) is released if you continue to experience the issue.

**Closed** 2022-03-05 19:41 UTC
Labels: bug, passed-dev-qa, gitpod-breaking-change

**Comment by strausmann** [comment] 2022-03-06 10:08
@apolopena 
Sorry. forgot to give feedback. :-)
With the new base image from GitPod my LE problem is also fixed.

![image](https://user-images.githubusercontent.com/4519228/156918710-79eb2a2a-050d-4ec9-bc5c-4dde01ef1268.png)
